# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-07-04 16:04
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0004_auto_20180705_0003'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='menu',
            options={'verbose_name': '菜单', 'verbose_name_plural': '菜单'},
        ),
        migrations.AlterModelTable(
            name='menu',
            table='菜单',
        ),
    ]
