# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-07-09 15:27
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0006_auto_20180705_1135'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customerinfo',
            options={},
        ),
    ]
