# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-07-16 13:26
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0011_auto_20180716_2113'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='studentenrollment',
            unique_together=set([]),
        ),
        migrations.RemoveField(
            model_name='studentenrollment',
            name='class_grade',
        ),
        migrations.RemoveField(
            model_name='studentenrollment',
            name='consultant',
        ),
        migrations.RemoveField(
            model_name='studentenrollment',
            name='customer',
        ),
        migrations.AddField(
            model_name='student',
            name='consultant',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='student',
            name='contract_agreed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='student',
            name='contract_approved',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='student',
            name='contract_approved_time',
            field=models.DateTimeField(blank=True, null=True, verbose_name='合同审核时间'),
        ),
        migrations.AddField(
            model_name='student',
            name='contract_signed_time',
            field=models.DateTimeField(blank=True, null=True, verbose_name='合同签订时间'),
        ),
        migrations.AlterField(
            model_name='paymentrecord',
            name='enrollment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crm.Student'),
        ),
        migrations.DeleteModel(
            name='StudentEnrollment',
        ),
    ]
