# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-07-16 13:31
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0012_auto_20180716_2126'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentEnrollment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contract_agreed', models.BooleanField(default=False)),
                ('contract_signed_time', models.DateTimeField(blank=True, null=True, verbose_name='合同签订时间')),
                ('contract_approved', models.BooleanField(default=False)),
                ('contract_approved_time', models.DateTimeField(blank=True, null=True, verbose_name='合同审核时间')),
                ('class_grade', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crm.ClassList')),
                ('consultant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crm.CustomerInfo')),
            ],
        ),
        migrations.RemoveField(
            model_name='student',
            name='consultant',
        ),
        migrations.RemoveField(
            model_name='student',
            name='contract_agreed',
        ),
        migrations.RemoveField(
            model_name='student',
            name='contract_approved',
        ),
        migrations.RemoveField(
            model_name='student',
            name='contract_approved_time',
        ),
        migrations.RemoveField(
            model_name='student',
            name='contract_signed_time',
        ),
        migrations.AlterField(
            model_name='paymentrecord',
            name='enrollment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crm.StudentEnrollment'),
        ),
        migrations.AlterUniqueTogether(
            name='studentenrollment',
            unique_together=set([('customer', 'class_grade')]),
        ),
    ]
