# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-07-19 00:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0017_remove_contracttemplate_class_grade'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentenrollment',
            name='contract_agreed',
            field=models.BooleanField(default=False, verbose_name='同意条款'),
        ),
        migrations.AlterField(
            model_name='studentenrollment',
            name='contract_approved',
            field=models.BooleanField(default=False, verbose_name='审核通过'),
        ),
    ]
