# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-07-17 02:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0013_auto_20180716_2131'),
    ]

    operations = [
        migrations.AddField(
            model_name='customerinfo',
            name='age',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='customerinfo',
            name='emergency_contact',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='customerinfo',
            name='gender',
            field=models.IntegerField(blank=True, choices=[(0, '男'), (1, '女')], null=True),
        ),
        migrations.AddField(
            model_name='customerinfo',
            name='id_num',
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
    ]
