# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-07-04 11:50
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='branch',
            options={'verbose_name': '校区', 'verbose_name_plural': '校区'},
        ),
        migrations.AlterModelOptions(
            name='student',
            options={'verbose_name': '学生', 'verbose_name_plural': '学生'},
        ),
        migrations.AlterModelOptions(
            name='studyrecord',
            options={'verbose_name': '学习记录', 'verbose_name_plural': '学习记录'},
        ),
        migrations.AlterModelTable(
            name='branch',
            table='校区',
        ),
        migrations.AlterModelTable(
            name='student',
            table='学生',
        ),
        migrations.AlterModelTable(
            name='studyrecord',
            table='学习记录',
        ),
    ]
