# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-07-20 23:02
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0018_auto_20180719_0023'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='class_grade',
        ),
        migrations.RemoveField(
            model_name='student',
            name='customer',
        ),
        migrations.AlterField(
            model_name='studyrecord',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crm.StudentEnrollment'),
        ),
        migrations.DeleteModel(
            name='Student',
        ),
    ]
