# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-07-21 13:28
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0020_auto_20180720_2309'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='classlist',
            name='teachers',
        ),
        migrations.AddField(
            model_name='classlist',
            name='teacher',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
